### ISSUE TITLE
fastener count on the FMJ document is wrong (is probably 1/2 needed)

### ISSUE THREAD

**Issue by joshmurrah** [MillenniumMachines/millenniummachines.github.io#25]
**Describe the bug**
The FMJ document has a BOM with number of fasteners - the number of fasteners is really short, it's probably the count for one plate and not both.

**Document Name / Location**
(https://millenniummachines.github.io/docs/milo/assembly_manual/chapters/fmj_assembly/#fmj-installation)

**Required Resolution**
adjust fastener count - I show 34 shown in the document photo, so BOM should be 68 - but adjust as needed.

**Screenshots**
![image](https://github.com/MillenniumMachines/millenniummachines.github.io/assets/72953857/0cc4821f-5817-4b44-9fee-05d1a935c17d)

**Comment by EdwardChamberlain** [comment]
Thanks - corrected to 68 (34 per side) as per image. 

This will show up when the dev docs merge to main.

**Comment by dmason1992** [comment]
#23 fixes this
