### ISSUE TITLE
Y Axis Bearing Block STL isn't named with [a] even though it's an accent piece

### ISSUE THREAD

**Issue by Burgestrand** [MillenniumMachines/millenniummachines.github.io#35]
This should probably be reported in the non-docs repository https://github.com/MillenniumMachines/Milo-v1.5 but the templates don't fit this issue, it's not a CAD bug nor a feature request.

**Describe the bug**
On the renders, [and in the documentation](https://github.com/MillenniumMachines/millenniummachines.github.io/blob/dd6d18f9965d4bad320bc7c0513b14fdcd4ed840/docs/milo/printing/print_guide.md?plain=1#L63), the Y Axis Bearing Block is supposed to be printed in accent color.

The STL in the Milo repo isn't named accordingly with `[a]`.

**Document Name / Location**
[STL Files/Minimill Main/Y Axis STLs/Y Axis Bearing Block x1.stl](https://github.com/MillenniumMachines/Milo-v1.5/blob/c3b967a13b8dbdeabb33892526dcdc6cc7563381/STL%20Files/Minimill%20Main/Y%20Axis%20STLs/Y%20Axis%20Bearing%20Block%20x1.stl)

**Required Resolution**
Rename the STL.

**Comment by EdwardChamberlain** [comment]
Thanks - will update.
