### ISSUE TITLE
BOM error for M5 T-nuts

### ISSUE THREAD

**Issue by jakep82** [MillenniumMachines/millenniummachines.github.io#9]
I'm in the middle of building a stock (non FMJ) Milo, and I bought a fastener kit from DFH.  The kit includes extras, but even with the extras I came up way short.  I counted up what I've used and what I still need to arrive at 120.  The Z axis alone requires 56 (28 per side) just to assemble it and attach to the Y axis without the Z chain mounts.  Add in 36 for the X table and I'm already past the 90 on the BOM.

**Comment by dmason1992** [comment]
@EdwardChamberlain should add the equivalent (FMJ) amount to the BOM for these. Sorry missed it in my review
